services:
  app:
    build:
      context: .              # racine du projet
      dockerfile: Dockerfile  # Dockerfile Ã  la racine
    container_name: ciblorgasport-back
    ports:
      - "1001:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/glop
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db

  db:
    image: postgres:16.10-bookworm
    container_name: postgresql_database
    environment:
      POSTGRES_DB: glop
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
